version: '3.9'

services:
  api:
    build:
      context: ./server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      demo_HOST: 0.0.0.0
      demo_DB_HOST: demo-db
      demo_DB_PORT: 5432
      demo_DB_USER: demo
      demo_DB_PASS: demo
      demo_DB_BASE: demo
    ports:
    - 8000:8000
  db:
    image: postgres:13.8-bullseye
    hostname: demo-db
    environment:
      POSTGRES_PASSWORD: "demo"
      POSTGRES_USER: "demo"
      POSTGRES_DB: "demo"
    volumes:
    - demo-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U demo
      interval: 2s
      timeout: 3s
      retries: 40
    ports:
    - 5432:5432
volumes:
  demo-db-data:
    name: demo-db-data
