"""drop question from contact

Revision ID: ea9e6561ed50
Revises:
Create Date: 2025-10-15 22:42:41.808133

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea9e6561ed50"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contact", "question")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contact",
        sa.Column("question", sa.TEXT(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
